[package]
name = "teos_governance"
version = "0.1.0"
edition = "2021"

[lib]
name = "teos_governance"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
default = []

[dependencies]
anchor-lang = "0.29.0"   # Anchor framework
solana-program = "1.18.0" # Solana runtime
